{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.target.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laravel_backend_helm.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  dataFrom:
    {{- toYaml .Values.externalSecret.dataFrom | nindent 4 }}
{{- end }}
