{{- if .Values.secret.enabled | default false }}
{{- range .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel_backend_helm.fullname" $ }}-{{ .name }}
  labels:
    {{- include "laravel_backend_helm.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
